{#-
  The interpreter's opcode case arms, token sub-switches, runtime guards, and
  the opcode summary are GENERATED by
  src/lowering/quotient_numerator/vm/yul_arms.rs from the same Q_OP_*/Q_MEM_*
  constants the encoder and the checked decoder use, and spliced below via
  program.op_summary_lines / program.vm_switch_arms (P4). The guard rationale
  (P12 operand clamps, MF-3 fail-closed guards) lives in that module's docs;
  the committed all-ops snapshot is
  templates/partials/quotient_numerator/vm_arms.snapshot.yul.
#}
            // __phase:quotient_vm
            // ===============================================================
            // Batched identity numerator / linearization target.
            //
            // This block does not evaluate the quotient polynomial h(x), and
            // the proof does not provide an h(x) scalar to trust. Instead it:
            //
            //   1. Reconstructs the y-batched constraint numerator nu_y(x)
            //      from the alleged polynomial evaluations read after the
            //      transcript sampled x.
            //   2. Stores -nu_y(x) as the expected opening scalar for the
            //      linearized commitment.
            //
            // The commitment side is built in the next block from the quotient
            // limb commitments as (1 - x^n) * Σ_i x_split^i * Q_i, plus any
            // simple-selector commitments. The PCS check later binds that
            // linearized commitment to this expected scalar at x.
            //
            // Rust source-of-truth:
            //   - verifier.rs reads quotient commitments, samples x, then
            //     reads/computes all evaluations used below.
            //   - mod.rs::partially_evaluate_identities returns identities in
            //     gate, permutation, lookup, trash order.
            //   - linearization/verifier.rs::compute_linearization_commitment
            //     reverse-folds those identities by powers of y, sends
            //     simple-selector identities to selector commitment scalars,
            //     and subtracts fully-evaluated identities into expected_eval.
            //
            // This template is shared by the monolithic and external quotient
            // paths. In the external path, Halo2QuotientEvaluator first copies
            // the verifier memory frame into the same generated addresses.
            //
            // Runtime inputs expected to exist before this block starts:
            //   - `r` is the BLS12-381 scalar-field modulus.
            //   - Y_MPTR holds the quotient batching challenge y.
            //   - X_MPTR, L_*_MPTR, INSTANCE_EVAL_MPTR, and
            //     REVERSED_EVALS_MPTR hold values parsed or derived by the
            //     main verifier after the transcript sampled x.
            //   - VK_MPTR holds the pinned VK payload; in compact mode that
            //     payload includes the quotient constant table and bytecode.
            //
            // Runtime outputs written by this block:
            //   - LINEARIZATION_EVAL_MPTR receives the scalar expected opening for
            //     the linearized commitment, namely -nu_y(x).
            //   - SELECTOR_ACC_MPTR[0..num_simple_selectors) receives one
            //     linearization scalar per generated simple selector.
            //
            // Line-by-line reading conventions used below:
            //
            //   * Every runtime value is one canonical Fr element stored in a
            //     256-bit EVM memory word. The small integer operands decoded
            //     from q_program are never field values; they are pointers,
            //     constant-table slots, selector indexes, offsets, or counts.
            //
            //   * `mload(ptr)` is the only way the VM turns a small pointer
            //     operand into a real 255-bit field element. The value loaded
            //     from memory is then combined with `addmod(..., r)` or
            //     `mulmod(..., r)`, so every arithmetic line is reduced modulo
            //     the BLS12-381 scalar-field order.
            //
            //   * `q_top` is the cached top of the VM operand stack. When an
            //     opcode needs to push while `q_top` is already live, the old
            //     value is written to `q_sp` and `q_sp` is advanced by one
            //     word. Binary `ADD`/`MUL` move `q_sp` back by one word and
            //     combine that spilled value with `q_top`.
            //
            //   * Identity boundaries are explicit. Expression opcodes leave
            //     one value in `q_top`; `FOLD_MAIN` or `FOLD_SELECTOR` consumes
            //     it and advances the global y-batch position. Native callback
            //     opcodes are only emitted at empty-stack boundaries and run
            //     generated Yul that performs the same fold side effects.
            //
            //   * The generated Solidity source intentionally emits comments
            //     before opcode cases. Those comments are documentation only:
            //     they do not affect bytecode, but they make rendered verifier
            //     assembly readable without jumping back to Rust codegen.
            // ===============================================================
            {
                {%- match quotient_program %}
                {%- when Some with (program) %}
                // Compact quotient-program mode.
                //
                // The largest identity expressions are not all emitted as
                // unrolled Yul. Instead, most arithmetic is encoded as a small
                // q_program bytecode stored in the VK payload. This block
                // interprets that program, while selected heavy identities may
                // still be emitted as native callbacks for gas.
                //
                // Compact mode is a code-size trade: short bytecode operands
                // name already-planned memory slots, and the interpreter turns
                // those names into Fr arithmetic. The opcode stream is fully
                // generated and pinned by the VK/runtime codehash; no proof
                // calldata can alter control flow.
                // Load the quotient batching challenge used by every fold.
                let y := mload(Y_MPTR)

                // q_const_mptr points to Fr constants used by the VM.
                // q_program_mptr points to the bytecode stream.
                // Constants are stored as consecutive 32-byte Fr words.
                let q_const_mptr := {{ program.const_mptr|hex() }}
                // Program bytes are also stored in the VK payload, packed into
                // 32-byte words by PackedProgramCodec.
                let q_program_mptr := {{ program.program_mptr|hex() }}
                // Running Horner accumulator for fully evaluated identities.
                // After all identities, this is nu_y(x) for the `None`
                // identity group.
                // Initialize A = 0 before scanning the identity stream.
                mstore({{ program.eval_numer_mptr|hex() }}, 0)
                {%- if self.trace %}
                // Trace builds label each emitted identity in y-batch order.
                mstore({{ program.trace_id_mptr|hex() }}, {{ quotient_identity_trace_base }})
                {%- endif %}
                {%- if simple_selector_cols.len() > 0 %}
                // Simple selectors are grouped into separate linearization
                // buckets. They start at zero for every proof.
                // q_sel_zero_off walks selector bucket byte offsets.
                for { let q_sel_zero_off := 0 } lt(q_sel_zero_off, {{ (simple_selector_cols.len() * 0x20)|hex() }}) { q_sel_zero_off := add(q_sel_zero_off, 0x20) } {
                    // B_s = 0 for each simple selector bucket.
                    mstore(add(SELECTOR_ACC_MPTR, q_sel_zero_off), 0)
                }

                {%- if program.selector_max_power > 0 %}
                // Codegen knows the selector identity positions. Precompute
                // the y^k powers needed for selector gap and tail updates,
                // avoiding a runtime y^-1 modexp and per-identity selector
                // scale maintenance.
                {
                    // q_y_power holds y^i at the current loop index.
                    let q_y_power := 1
                    // Slot 0 holds y^0 = 1. Codegen never emits a read of it
                    // (FOLD_SELECTOR guards on a nonzero gap, and
                    // selector_tail_updates drops zero tails), but the tail
                    // block multiplies by mload(selector_power_mptr + offset)
                    // unconditionally -- so initialize the slot rather than
                    // leaving correctness to two filters in another file.
                    mstore({{ program.selector_power_mptr|hex() }}, 1)
                    // Start at i=1 because y^0 = 1 is written above.
                    for { let q_y_power_i := 1 } lt(q_y_power_i, {{ program.selector_max_power + 1 }}) { q_y_power_i := add(q_y_power_i, 1) } {
                        // Advance from y^(i-1) to y^i modulo Fr.
                        q_y_power := mulmod(q_y_power, y, r)
                        // Store y^i at selector_power_mptr + 32*i.
                        mstore(add({{ program.selector_power_mptr|hex() }}, shl(5, q_y_power_i)), q_y_power)
                    }
                }
                {%- endif %}
                {%- endif %}

                // Direct inline prefix. These identities are generated as Yul
                // before entering the VM. They use the same fold snippets as
                // VM/native identities, so they occupy the same y-batch order.
                {%- for code_block in quotient_inline_computations %}
                {%- for line in code_block %}
                {{ line }}
                {%- endfor %}
                {%- endfor %}

                // VM registers:
                //   q_pc      current bytecode pointer
                //   q_end     end of bytecode stream
                //   q_sp      memory stack pointer for non-top stack values
                //   q_top     cached top-of-stack value
                //   q_has_top whether q_top currently holds a stack value
                //
                // The cached top reduces memory traffic in the interpreter.
                // q_sp's registered range must cover the interpreted operand
                // stack plus any native callback scratch that reuses this base
                // pointer. In particular, the native permutation callback
                // writes a structured scratch table at program.stack_mptr.
                // q_pc starts at the first encoded instruction.
                let q_pc := q_program_mptr
                // q_end is an exclusive byte pointer for the VM loop.
                let q_end := add(q_program_mptr, {{ program.len|hex() }})
                // q_sp starts at the first free stack word.
                let q_sp := {{ program.stack_mptr|hex() }}
                // q_top is meaningless until q_has_top is set.
                let q_top := 0
                // q_has_top = 0 means the VM stack is empty.
                let q_has_top := 0

                // q_program opcode summary. Rendered from the same
                // program.op_usage predicates that gate the interpreter's
                // case arms below, so this artifact documents exactly the
                // opcodes its program can contain -- no more, no fewer.
                {%- for line in program.op_summary_lines %}
{{ line }}
                {%- endfor %}
                //
                // The default IVC verifier uses one physical encoding for the
                // logical VM: compact byte-oriented opcodes with variable-width
                // operands, dynamic runs, and limb-aware cases.
                {#
                Template-only switch/case reference.

                This comment documents the interpreter source without being
                emitted into generated Solidity. Runtime behavior lives in the
                switch blocks below; opcode numbers and operand layouts are
                defined in src/lowering/quotient_numerator/vm/mod.rs.

                Shared stack model:
                - q_top caches the top stack value.
                - q_has_top records whether q_top is live.
                - q_sp points just past spilled stack words.
                - push-like cases spill the old q_top when q_has_top is set.
                - ADD/MUL pop by moving q_sp back one word.
                - accumulator cases mutate q_top in place.
                - FOLD_* cases consume q_top and advance the y-batch state.
                - native callbacks reset q_top/q_sp and perform their own
                  fold calls inside generated callback code.

                Case map:
                0x01 push_const
                  bytes:    u16 const_idx
                  effect:   push q_const_mptr[const_idx]

                0x02 push_mem_literal
                  bytes:    u32 ptr
                  effect:   push mload(ptr)

                0x03 push_mem_token
                  bytes:    u8 token
                  effect:   resolve token to a generated pointer and push it

                0x04 push_mem_token_offset
                  bytes:    u8 token, u32 offset
                  effect:   resolve token, add byte offset, and push mload

                0x05 push_mem_u16
                  bytes:    u16 ptr
                  effect:   compact pointer load

                0x06 add
                  effect: q_top = stack_pop() + q_top mod Fr

                0x07 mul
                  effect: q_top = stack_pop() * q_top mod Fr

                0x08 neg
                  effect: q_top = -q_top mod Fr

                0x09 push_const_u8
                  bytes:    u8 const_idx
                  effect:   short form of push_const

                0x0a fold_main
                  effect: trace q_top, advance q_eval_numer = q_eval_numer*y
                          + q_top

                0x0b fold_selector
                  bytes:    u8 selector_idx, u16 selector_gap
                  effect: trace q_top, advance the global y position, and add
                          q_top into a selector bucket after applying its
                          codegen-known y^gap

                0x0c add_const_u8
                  effect: q_top += q_const_mptr[u8 const_idx]

                0x0d mul_const_u8
                  effect: q_top *= q_const_mptr[u8 const_idx]

                0x0e add_const
                  effect: q_top += q_const_mptr[u16 const_idx]

                0x0f mul_const
                  effect: q_top *= q_const_mptr[u16 const_idx]

                0x10 add_mem_u16
                  effect: q_top += mload(u16 ptr)

                0x11 mul_mem_u16
                  effect: q_top *= mload(u16 ptr)

                0x12 add_mul_mem_mem_const_u8
                  bytes:    u16 lhs, u16 rhs, u8 const_idx
                  effect:   q_top += mload(lhs) * mload(rhs) * const

                0x13 add_mul_const_u8_mem_u16
                  bytes:    u16 ptr, u8 const_idx
                  effect:   q_top += mload(ptr) * const

                0x14 add_mul_mem_mem
                  bytes:    u16 lhs, u16 rhs
                  effect:   q_top += mload(lhs) * mload(rhs)

                0x15 run_add_mul_mem_mem_const_u8
                  bytes: u16 count, then count * {u16 lhs, u16 rhs, u8 c}
                  effect: repeated 0x12 in one dispatch

                0x16 run_add_mul_const_u8_mem_u16
                  bytes: u16 count, then count * {u16 ptr, u8 c}
                  effect: repeated 0x13 in one dispatch

                0x22 affine_sum
                  bytes: u16 lin_count, u16 product_count,
                    lin_count * {u16 ptr, u8 c},
                    product_count * {u16 lhs, u16 rhs, u8 c}
                  effect: q_top += sum c_i * mload(p_i)
                    + sum c_i * mload(p_i) * mload(q_i)

                0x19 native_permutation
                  effect: evaluate and fold the generated permutation identity
                          family at this VM stream position

                0x1a reserved
                  effect: no switch case; default branch reverts

                0x1b native_identity
                  effect: dispatch to one generated heavy-gate callback by index

                0x1c lin7
                  bytes: seven {u8 const_idx, u16 ptr} pairs
                  effect: push sum_i const_i * mload(ptr_i)

                0x1d bilin7_row
                  bytes: u16 lhs, seven {u8 const_idx, u16 rhs} pairs
                  effect: push mload(lhs) * sum_i const_i * mload(rhs_i)

                0x1e bilin7_pairwise
                  bytes: u16 lhs_base, u16 rhs_base, 13 const indexes
                  effect: push sum_{i,j} const_{i+j} * lhs_i * rhs_j

                0x1f native_lookup
                  effect: evaluate and fold LogUp boundary/helper/accumulator
                          identities at this VM stream position

                0x20 pow5
                  effect: q_top = q_top^5

                0x21 modarith7
                  bytes: flags, optional cond/constant, count header,
                              then fused LIN7/BILIN7/mem/product blocks
                  effect: push one fused affine 7-limb identity value

                Memory token map used by 0x03/0x04:
                0x01 L_0_MPTR
                0x02 L_LAST_MPTR
                0x03 L_BLIND_MPTR
                0x04 BETA_MPTR
                0x05 GAMMA_MPTR
                0x06 X_MPTR
                0x07 THETA_MPTR
                0x08 TRASH_CHALLENGE_MPTR
                0x09 INSTANCE_EVAL_MPTR
                #}
                // Byte-oriented encoding: opcodes are one byte followed by
                // variable-width operand bytes.
                for { } lt(q_pc, q_end) { } {
                    // The bytecode table is byte-addressed, but EVM memory
                    // loads whole words. `byte(0, mload(q_pc))` extracts the
                    // opcode at the current byte cursor; each case advances
                    // q_pc by exactly its operand width.
                    let q_op := byte(0, mload(q_pc))
                    q_pc := add(q_pc, 1)

                    switch q_op
                    {%- for arm_line in program.vm_switch_arms %}
{{ arm_line }}
                    {%- endfor %}
                    // Invalid generated bytecode should fail closed. 0x1a intentionally lands here.
                    default {
                        q_program_fail()
                    }
                }
                // The VK-pinned bytecode must end exactly at q_end and every
                // identity must have been consumed by a fold/native callback.
                // This catches malformed generator output whose final opcode
                // over-reads operands or leaves a partial expression live.
                if iszero(eq(q_pc, q_end)) { q_program_fail() }
                if q_has_top { q_program_fail() }
                // The spilled stack must also be balanced. A FOLD executed
                // with more than one operand live consumes only the cached
                // top, leaving abandoned words below q_sp with q_has_top
                // clear -- so both checks above pass while an operand of the
                // identity has been silently dropped from nu_y(x).
                if iszero(eq(q_sp, {{ program.stack_mptr|hex() }})) { q_program_fail() }

                // Structured post-VM suffix. The current default uses this for
                // regular trash constraints: it is smaller than fully unrolled
                // Yul and cheaper than interpreting every trash operation.
                //
                // These generated blocks run after q_pc reaches q_end, but
                // they still participate in the same identity order and write
                // into the same numerator / selector accumulators.
                {%- for code_block in quotient_post_vm_computations %}
                {%- for line in code_block %}
                {{ line }}
                {%- endfor %}
                {%- endfor %}

                {%- if simple_selector_cols.len() > 0 %}
                // Finish selector buckets by applying the codegen-known tail
                // from each selector's last identity to the end of the global
                // y-batch.
                //
                // After this step, every selector bucket is aligned with the
                // final global y position and can be multiplied by its fixed
                // selector commitment in the linearized MSM.
                {%- for tail in program.selector_tail_updates %}
                {
                    let q_sel_ptr := add(SELECTOR_ACC_MPTR, {{ tail.selector_offset|hex() }})
                    mstore(q_sel_ptr, mulmod(mload(q_sel_ptr), mload(add({{ program.selector_power_mptr|hex() }}, {{ tail.power_offset|hex() }})), r))
                }
                {%- endfor %}
                {%- endif %}

                // Fully evaluated identities are the constant-polynomial side
                // of the linearization query. Rust subtracts that grouped
                // scalar into expected_eval, so Solidity stores -nu_y(x).
                let linearization_expected_eval := addmod(0, sub(r, mload({{ program.eval_numer_mptr|hex() }})), r)
                mstore(LINEARIZATION_EVAL_MPTR, linearization_expected_eval)
                pop(y)
                {%- when None %}
                // Legacy/direct mode. This path emits the numerator
                // reconstruction directly instead of interpreting q_program.
                // It is used by older monolithic/experimental generation
                // modes and remains available as a fallback for models that do
                // not carry compact quotient bytecode.
                //
                // The generated statements in quotient_eval_numer_computations
                // are already ordered and folded by the Rust renderer. They
                // must leave `quotient_eval_numer` as nu_y(x), matching the
                // compact VM accumulator in program.eval_numer_mptr.
                let delta := {{ fr_delta }} // BLS12-381 Fr::DELTA
                let y := mload(Y_MPTR)
                {%- if self.trace %}
                // Direct mode increments q_trace_id inside generated fold
                // snippets, mirroring compact-mode trace_id_mptr.
                let q_trace_id := {{ quotient_identity_trace_base }}
                {%- endif %}

                // Direct/generated numerator body. This may contain unrolled
                // gate, permutation, lookup, trash, and selector-fold code.
                {%- for code_block in quotient_eval_numer_computations %}
                {%- for line in code_block %}
                {{ line }}
                {%- endfor %}
                {%- endfor %}

                // Silence Yul unused-variable warnings in renders where the
                // direct body did not need one of these common constants.
                pop(y)
                pop(delta)

                // Store the expected opening scalar for the linearized
                // commitment at x: the negated sum of fully-evaluated
                // identities. See
                // `compute_linearization_commitment` in
                // midfall/proofs/src/plonk/linearization/verifier.rs:
                //
                //   expected_eval -= eval     (for col_idx == None)
                //
                // The commitment side already includes the quotient-limb
                // factor (1 - x^n), so this scalar is -nu_y(x), not
                // h(x) = nu_y(x) / (x^n - 1).
                let linearization_expected_eval := addmod(0, sub(r, quotient_eval_numer), r)
                mstore(LINEARIZATION_EVAL_MPTR, linearization_expected_eval)
                {%- endmatch %}
            }
