// SPDX-License-Identifier: CC0-1.0
//! Curve-level adversarial replay against the **deployed** Sepolia artifacts.
//!
//! This complements `tests/ivc_accumulator_replay.rs` rather than repeating it.
//! That file already covers limb packing, calldata framing, EIP-2537 pad-byte
//! canonicality, scalar canonicality, instance binding, and the four infinity
//! encodings. What it never does is hand the verifier a point that is
//! *correctly encoded and on the curve* but wrong in some deeper way.
//!
//! That gap matters because of an explicit design decision documented at
//! `common_uncompressed_g1`: the verifier runs no on-curve and no subgroup
//! check of its own, and defers both to the EIP-2537 precompiles on the
//! grounds that every absorbed commitment is later consumed by a G1MSM or a
//! pairing. Nothing executes that claim. Every mutation in the existing suite
//! is caught earlier, by a range or packing or transcript guard, so the
//! precompile validation layer has never been observed rejecting anything.
//!
//! The cases below are built to reach it:
//!
//! - a point on `y^2 = x^3 + 4` that is **outside** the r-order subgroup,
//!   substituted for accumulator points and for proof commitments;
//! - `(0, 2)`, the only curve point with `x = 0` -- h-torsion, and the one
//!   value that collides with the codec's `p - 1` zero sentinel;
//! - points that are fully valid G1 elements but the *wrong* elements (the
//!   generator, and the negation of the fixture's own accumulator), which
//!   pass every encoding, curve and subgroup check and can only fail at the
//!   final pairing;
//! - coordinate encodings that decode to at least `p`;
//! - over-packing of the *second* coordinate word (3 limbs = 168 bits), where
//!   the existing suite only over-packs the first (4 limbs = 224 bits).
//!
//! Target: the sources under `deployments/sepolia/moonlight-wrap/`, i.e. the
//! bytecode actually on chain, not the newer `fixtures/moonlight-wrap/` render.
//! The two share a proof layout (`0x1e60` bytes, 19 instances, identical VK
//! header and commitments; they differ only in the VK's quotient-program
//! encoding), so the fixture calldata is a valid input for both.
//!
//! Vectors are generated by construction and asserted against the codec, so
//! there are no magic constants that could drift from the artifacts.

#![cfg(feature = "evm")]

use halo2_solidity_verifier::{
    compile_solidity_with_runs, revm::primitives::Address, CallOutcome, Evm,
};
use std::path::PathBuf;

const SOLC_OPTIMIZE_RUNS: u32 = 200;
const GAS_CAP: u64 = 60_000_000;

/// BLS12-381 base field modulus.
const P_HEX: &str = "1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab";

/// Accumulator codec parameters, pinned by the deployed verifier at
/// `Halo2Verifier.sol:933-934` (`num_acc_limbs = 7`, `num_acc_limb_bits = 56`).
const LIMB_BITS: u32 = 56;
const NUM_LIMBS: usize = 7;
const LIMBS_PER_WORD: usize = 4;
/// `acc_offset = 11`: the accumulator occupies the trailing 8 of 19 instances.
const ACC_OFFSET: usize = 11;
/// Calldata cursors, from the deployed verifier's constants.
const PROOF_START: usize = 0x64;
const PROOF_LEN: usize = 0x1e60;
const INSTANCE_START: usize = 0x1ee4;

// ---------------------------------------------------------------------------
// Minimal BLS12-381 G1 arithmetic over the integers. Only enough to build
// adversarial points; correctness is self-checked below.
// ---------------------------------------------------------------------------

type Big = num_bigint::BigUint;

fn p() -> Big {
    Big::parse_bytes(P_HEX.as_bytes(), 16).expect("modulus should parse")
}

fn r_order() -> Big {
    Big::parse_bytes(
        b"73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001",
        16,
    )
    .expect("scalar modulus should parse")
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum Pt {
    Inf,
    Aff(Big, Big),
}

fn f_sub(a: &Big, b: &Big) -> Big {
    let m = p();
    ((a % &m) + &m - (b % &m)) % &m
}

fn f_inv(a: &Big) -> Big {
    let m = p();
    a.modpow(&(&m - Big::from(2u32)), &m)
}

fn pt_add(lhs: &Pt, rhs: &Pt) -> Pt {
    let m = p();
    match (lhs, rhs) {
        (Pt::Inf, q) => q.clone(),
        (q, Pt::Inf) => q.clone(),
        (Pt::Aff(x1, y1), Pt::Aff(x2, y2)) => {
            if x1 == x2 && (y1 + y2) % &m == Big::from(0u32) {
                return Pt::Inf;
            }
            let lam = if lhs == rhs {
                (Big::from(3u32) * x1 * x1 % &m) * f_inv(&(Big::from(2u32) * y1 % &m)) % &m
            } else {
                f_sub(y2, y1) * f_inv(&f_sub(x2, x1)) % &m
            };
            let x3 = f_sub(&f_sub(&(&lam * &lam % &m), x1), x2);
            let y3 = f_sub(&(&lam * f_sub(x1, &x3) % &m), y1);
            Pt::Aff(x3, y3)
        }
    }
}

fn pt_mul(pt: &Pt, k: &Big) -> Pt {
    let mut acc = Pt::Inf;
    for bit in format!("{k:b}").chars() {
        acc = pt_add(&acc, &acc);
        if bit == '1' {
            acc = pt_add(&acc, pt);
        }
    }
    acc
}

fn on_curve(x: &Big, y: &Big) -> bool {
    let m = p();
    (y * y) % &m == (x * x % &m * x + Big::from(4u32)) % &m
}

fn in_subgroup(pt: &Pt) -> bool {
    pt_mul(pt, &r_order()) == Pt::Inf
}

/// `p % 4 == 3`, so a square root is `a^((p+1)/4)` when one exists.
fn sqrt_f(a: &Big) -> Option<Big> {
    let m = p();
    let s = a.modpow(&((&m + Big::from(1u32)) / Big::from(4u32)), &m);
    (&s * &s % &m == a % &m).then_some(s)
}

/// Smallest-x curve point that is **not** in the r-order subgroup. A random
/// on-curve point lies in G1 with probability 1/h, so this terminates at once;
/// the subgroup check below is what makes the vector trustworthy rather than
/// the search.
fn non_subgroup_point() -> (Big, Big) {
    let m = p();
    for x in 1u32..10_000 {
        let xb = Big::from(x);
        let rhs = (&xb * &xb % &m * &xb + Big::from(4u32)) % &m;
        let Some(y) = sqrt_f(&rhs) else { continue };
        if !on_curve(&xb, &y) {
            continue;
        }
        if in_subgroup(&Pt::Aff(xb.clone(), y.clone())) {
            continue;
        }
        return (xb, y);
    }
    panic!("no non-subgroup point found in the search range");
}

fn generator() -> (Big, Big) {
    (
        Big::parse_bytes(b"17f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb", 16).unwrap(),
        Big::parse_bytes(b"08b3f481e3aaa0f1a09e30ed741d8ae4fcf5e095d5d00af600db18cb2c04b3edd03cc744a2888ae40caa232946c5e7e1", 16).unwrap(),
    )
}

// ---------------------------------------------------------------------------
// The accumulator public-input codec (midnight-circuits
// `AssignedForeignPoint::as_public_input`): publish `(coord - 1) mod p` as
// seven radix-2^56 limbs, packed four-then-three into two native words.
// ---------------------------------------------------------------------------

fn encode_coord(coord: &Big) -> (Big, Big) {
    let m = p();
    let e = f_sub(coord, &Big::from(1u32));
    let mask = (Big::from(1u32) << LIMB_BITS) - Big::from(1u32);
    let limb = |i: usize| (&e >> (LIMB_BITS * i as u32)) & &mask;
    let mut w0 = Big::from(0u32);
    for i in 0..LIMBS_PER_WORD {
        w0 |= limb(i) << (LIMB_BITS * i as u32);
    }
    let mut w1 = Big::from(0u32);
    for i in LIMBS_PER_WORD..NUM_LIMBS {
        w1 |= limb(i) << (LIMB_BITS * (i - LIMBS_PER_WORD) as u32);
    }
    debug_assert!(e < m);
    (w0, w1)
}

fn decode_coord(w0: &Big, w1: &Big) -> Big {
    let mask = (Big::from(1u32) << LIMB_BITS) - Big::from(1u32);
    let mut e = Big::from(0u32);
    for i in 0..LIMBS_PER_WORD {
        e |= ((w0 >> (LIMB_BITS * i as u32)) & &mask) << (LIMB_BITS * i as u32);
    }
    for i in LIMBS_PER_WORD..NUM_LIMBS {
        e |= ((w1 >> (LIMB_BITS * (i - LIMBS_PER_WORD) as u32)) & &mask) << (LIMB_BITS * i as u32);
    }
    if e == p() - Big::from(1u32) {
        Big::from(0u32)
    } else {
        e + Big::from(1u32)
    }
}

fn word_bytes(v: &Big) -> [u8; 32] {
    let raw = v.to_bytes_be();
    assert!(raw.len() <= 32, "value does not fit in one EVM word");
    let mut out = [0u8; 32];
    out[32 - raw.len()..].copy_from_slice(&raw);
    out
}

/// EIP-2537 padded uncompressed G1: 16 zero bytes then 48 big-endian bytes,
/// per coordinate, for 128 bytes total.
fn padded_g1(x: &Big, y: &Big) -> [u8; 128] {
    let mut out = [0u8; 128];
    for (slot, coord) in [(0usize, x), (64, y)] {
        let raw = coord.to_bytes_be();
        assert!(raw.len() <= 48, "coordinate does not fit in 48 bytes");
        out[slot + 64 - 48 + (48 - raw.len())..slot + 64].copy_from_slice(&raw);
    }
    out
}

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

fn deployment_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("deployments/sepolia/moonlight-wrap")
}

fn fixture_calldata() -> Vec<u8> {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/moonlight-wrap/calldata.bin");
    std::fs::read(&path).unwrap_or_else(|e| panic!("missing {}: {e}", path.display()))
}

/// Which layer rejected the input, inferred from gas. The three regimes are
/// far enough apart to be unambiguous: the envelope guards run before any
/// precompile, the full algebraic path costs about as much as an accepted
/// proof, and a precompile that rejects its input consumes everything it was
/// forwarded.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
enum Stage {
    /// Rejected by an ABI, canonicality, packing or decode guard.
    Guard,
    /// Decoded and absorbed fine; the algebra or the final pairing said no.
    Algebra,
    /// An EIP-2537 precompile rejected the point and burned the gas budget.
    Precompile,
}

fn classify(gas_used: u64, accepted_gas: u64) -> Stage {
    if gas_used > accepted_gas.saturating_mul(4) {
        Stage::Precompile
    } else if gas_used * 2 < accepted_gas {
        Stage::Guard
    } else {
        Stage::Algebra
    }
}

fn expect_reject(evm: &mut Evm, addr: Address, cd: Vec<u8>, accepted: u64, case: &str) -> Stage {
    match evm.try_call_with_gas(addr, cd, GAS_CAP) {
        CallOutcome::Success {
            output, gas_used, ..
        } => panic!(
            "{case}: ACCEPTED (gas {gas_used}, output 0x{}) -- this input must not verify",
            hex::encode(output)
        ),
        CallOutcome::Halt { reason, gas_used } => {
            panic!("{case}: halted ({reason}) after {gas_used} gas; expected a revert")
        }
        CallOutcome::Revert { gas_used, .. } => classify(gas_used, accepted),
    }
}

fn write_acc_point(cd: &mut [u8], point_index: usize, x: &Big, y: &Big) {
    let (xw0, xw1) = encode_coord(x);
    let (yw0, yw1) = encode_coord(y);
    assert_eq!(
        (decode_coord(&xw0, &xw1), decode_coord(&yw0, &yw1)),
        (x.clone(), y.clone()),
        "codec round-trip failed; the test vector would not mean what it claims"
    );
    let base = INSTANCE_START + (ACC_OFFSET + point_index * 4) * 32;
    for (i, w) in [xw0, xw1, yw0, yw1].iter().enumerate() {
        cd[base + i * 32..base + (i + 1) * 32].copy_from_slice(&word_bytes(w));
    }
}

fn acc_word_offset(point_index: usize, word: usize) -> usize {
    INSTANCE_START + (ACC_OFFSET + point_index * 4 + word) * 32
}

// ---------------------------------------------------------------------------

#[test]
fn deployed_wrap_verifier_rejects_curve_level_attacks() {
    let dir = deployment_dir();
    let vk_src = std::fs::read_to_string(dir.join("Halo2VerifyingKey.sol")).unwrap();
    let ver_src = std::fs::read_to_string(dir.join("Halo2Verifier.sol")).unwrap();
    let calldata = fixture_calldata();

    assert_eq!(
        calldata.len(),
        INSTANCE_START + 19 * 32,
        "fixture calldata does not match the deployed verifier's pinned envelope"
    );
    assert_eq!(
        PROOF_START + PROOF_LEN,
        0x1ec4,
        "proof layout constants disagree"
    );

    // --- vectors, each self-checked so a broken generator cannot silently
    // --- turn an assertion into a tautology -------------------------------
    let (nsx, nsy) = non_subgroup_point();
    assert!(
        on_curve(&nsx, &nsy),
        "non-subgroup vector must be on the curve"
    );
    assert!(
        !in_subgroup(&Pt::Aff(nsx.clone(), nsy.clone())),
        "non-subgroup vector must be outside G1, or it tests nothing"
    );

    let (h_x, h_y) = (Big::from(0u32), Big::from(2u32));
    assert!(on_curve(&h_x, &h_y), "(0,2) must be on the curve");
    assert!(
        !in_subgroup(&Pt::Aff(h_x.clone(), h_y.clone())),
        "(0,2) must be h-torsion"
    );

    let (gx, gy) = generator();
    assert!(
        in_subgroup(&Pt::Aff(gx.clone(), gy.clone())),
        "generator vector must be a valid G1 element, or the pairing test is vacuous"
    );

    // The fixture's own accumulator, recovered and re-encoded. This proves the
    // codec implemented here matches the one the circuit used.
    let read_word = |off: usize| Big::from_bytes_be(&calldata[off..off + 32]);
    let lhs_x = decode_coord(
        &read_word(acc_word_offset(0, 0)),
        &read_word(acc_word_offset(0, 1)),
    );
    let lhs_y = decode_coord(
        &read_word(acc_word_offset(0, 2)),
        &read_word(acc_word_offset(0, 3)),
    );
    assert!(
        on_curve(&lhs_x, &lhs_y) && in_subgroup(&Pt::Aff(lhs_x.clone(), lhs_y.clone())),
        "the fixture's own accumulator must decode to a valid G1 point; \
         if it does not, this file's codec is wrong and every vector below is meaningless"
    );
    let neg_lhs_y = f_sub(&p(), &lhs_y);

    // --- deploy the on-chain sources -------------------------------------
    let mut evm = Evm::default();
    let vk = evm.create(compile_solidity_with_runs(&vk_src, SOLC_OPTIMIZE_RUNS));
    assert_eq!(evm.code_size(vk), 17_025, "VK runtime size drifted");
    let verifier =
        evm.create_with_address_arg(compile_solidity_with_runs(&ver_src, SOLC_OPTIMIZE_RUNS), vk);
    assert_eq!(
        evm.code_size(verifier),
        21_161,
        "verifier runtime size drifted"
    );

    let accepted_gas = match evm.try_call_with_gas(verifier, calldata.clone(), GAS_CAP) {
        CallOutcome::Success {
            output, gas_used, ..
        } => {
            assert_eq!(
                output,
                [vec![0u8; 31], vec![1]].concat(),
                "an accepted proof must return exactly true"
            );
            gas_used
        }
        other => panic!(
            "the deployed contracts must accept the fixture proof, otherwise every \
             rejection below could be a rejection of everything: {other:?}"
        ),
    };

    let mut log: Vec<(String, Stage)> = Vec::new();
    let mut check = |evm: &mut Evm, cd: Vec<u8>, case: &str, want: Stage| {
        let got = expect_reject(evm, verifier, cd, accepted_gas, case);
        assert_eq!(got, want, "{case}: rejected at {got:?}, expected {want:?}");
        log.push((case.to_string(), got));
    };

    // =====================================================================
    // 1. Subgroup membership -- the check the verifier delegates entirely to
    //    EIP-2537 and that nothing else in the suite exercises.
    // =====================================================================
    for point in 0..2usize {
        let mut cd = calldata.clone();
        write_acc_point(&mut cd, point, &nsx, &nsy);
        check(
            &mut evm,
            cd,
            &format!("accumulator point {point} on the curve but outside the r-order subgroup"),
            Stage::Precompile,
        );
    }

    // Same attack on the proof side: every absorbed commitment is claimed to
    // reach a G1MSM. Substituting a non-subgroup point tests that claim for
    // the first commitment of each category in the deployed proof layout.
    let categories: [(&str, usize); 7] = [
        ("advice[0]", 0x0000),
        ("lookup_multiplicity[0]", 0x0780),
        ("permutation_z[0]", 0x0880),
        ("lookup_helper[0]", 0x0b80),
        ("trashcan[0]", 0x0d80),
        ("quotient_limb[0]", 0x0e00),
        ("f_com", 0x1cc0),
    ];
    let ns_padded = padded_g1(&nsx, &nsy);
    for (name, off) in categories {
        let mut cd = calldata.clone();
        cd[PROOF_START + off..PROOF_START + off + 128].copy_from_slice(&ns_padded);
        check(
            &mut evm,
            cd,
            &format!("{name} replaced with a non-subgroup curve point"),
            Stage::Precompile,
        );
    }

    // =====================================================================
    // 2. (0, 2) -- the only curve point with x = 0, which is exactly the
    //    value the codec's `p - 1` sentinel decodes to. h-torsion, so a
    //    correct verifier must reject it; and because x = 0 it is the one
    //    input where the zero sentinel and a real coordinate collide.
    // =====================================================================
    for point in 0..2usize {
        let mut cd = calldata.clone();
        write_acc_point(&mut cd, point, &h_x, &h_y);
        check(
            &mut evm,
            cd,
            &format!("accumulator point {point} set to the h-torsion point (0, 2)"),
            Stage::Guard,
        );
    }

    // =====================================================================
    // 3. Valid G1 elements, wrong values. These clear every encoding, curve
    //    and subgroup check, so only the pairing can reject them. If any of
    //    these were accepted, the accumulator would not be bound at all.
    // =====================================================================
    for point in 0..2usize {
        let mut cd = calldata.clone();
        write_acc_point(&mut cd, point, &gx, &gy);
        check(
            &mut evm,
            cd,
            &format!("accumulator point {point} replaced with the G1 generator"),
            Stage::Algebra,
        );
    }
    {
        let mut cd = calldata.clone();
        write_acc_point(&mut cd, 0, &lhs_x, &neg_lhs_y);
        check(
            &mut evm,
            cd,
            "accumulator lhs negated (still a valid G1 element)",
            Stage::Algebra,
        );
    }
    {
        // Both halves set to the same valid point: individually well-formed,
        // jointly degenerate.
        let mut cd = calldata.clone();
        write_acc_point(&mut cd, 1, &lhs_x, &lhs_y);
        check(
            &mut evm,
            cd,
            "accumulator lhs and rhs set to the same valid point",
            Stage::Algebra,
        );
    }

    // =====================================================================
    // 4. Coordinate encodings that decode outside the base field.
    // =====================================================================
    for point in 0..2usize {
        for (word, label) in [(0usize, "x"), (2, "y")] {
            let mut cd = calldata.clone();
            // Encoded value `p` decodes to `p + 1`, which is not a field
            // element and is not the `p - 1` zero sentinel either.
            let e = p();
            let mask = (Big::from(1u32) << LIMB_BITS) - Big::from(1u32);
            let mut w0 = Big::from(0u32);
            for i in 0..LIMBS_PER_WORD {
                w0 |= ((&e >> (LIMB_BITS * i as u32)) & &mask) << (LIMB_BITS * i as u32);
            }
            let mut w1 = Big::from(0u32);
            for i in LIMBS_PER_WORD..NUM_LIMBS {
                w1 |= ((&e >> (LIMB_BITS * i as u32)) & &mask)
                    << (LIMB_BITS * (i - LIMBS_PER_WORD) as u32);
            }
            assert!(
                decode_coord(&w0, &w1) >= p(),
                "vector must decode out of field"
            );
            let base = acc_word_offset(point, word);
            cd[base..base + 32].copy_from_slice(&word_bytes(&w0));
            cd[base + 32..base + 64].copy_from_slice(&word_bytes(&w1));
            check(
                &mut evm,
                cd,
                &format!("accumulator point {point} {label} decodes to a value >= p"),
                Stage::Guard,
            );
        }
    }

    // =====================================================================
    // 5. Over-packing the SECOND coordinate word. It carries three limbs, so
    //    bits 168..255 are unused; the existing suite only over-packs the
    //    first word's 224-bit boundary.
    // =====================================================================
    for point in 0..2usize {
        for (word, label) in [(1usize, "x"), (3, "y")] {
            let mut cd = calldata.clone();
            let off = acc_word_offset(point, word);
            let mut w = Big::from_bytes_be(&cd[off..off + 32]);
            w |= Big::from(1u32) << (LIMB_BITS * (NUM_LIMBS - LIMBS_PER_WORD) as u32);
            cd[off..off + 32].copy_from_slice(&word_bytes(&w));
            check(
                &mut evm,
                cd,
                &format!("accumulator point {point} {label} second word over-packed past bit 168"),
                Stage::Guard,
            );
        }
    }

    // =====================================================================
    // 6. Identity flag on `y`. Only `x` may carry it (`load_acc_coord` is
    //    called with `allow_id = 0` for `y`), so adding one radix base to
    //    the y word must not produce an accepted infinity.
    // =====================================================================
    for point in 0..2usize {
        let mut cd = calldata.clone();
        let off = acc_word_offset(point, 2);
        let w = Big::from_bytes_be(&cd[off..off + 32]) + (Big::from(1u32) << LIMB_BITS);
        cd[off..off + 32].copy_from_slice(&word_bytes(&w));
        check(
            &mut evm,
            cd,
            &format!("accumulator point {point} carries an identity flag on y"),
            Stage::Precompile,
        );
    }

    // =====================================================================
    // 7. Off-curve accumulator points that are otherwise perfectly encoded.
    // =====================================================================
    for point in 0..2usize {
        let mut cd = calldata.clone();
        // x from a real point, y from a different real point: canonical
        // field elements, correct packing, not on the curve.
        write_acc_point(&mut cd, point, &lhs_x, &gy);
        check(
            &mut evm,
            cd,
            &format!(
                "accumulator point {point} has canonical coordinates that are not on the curve"
            ),
            Stage::Precompile,
        );
    }

    // --- report -----------------------------------------------------------
    println!("\naccepted baseline: {accepted_gas} gas\n");
    println!("{:<74}  rejected by", "case");
    for (case, stage) in &log {
        println!("{case:<74}  {stage:?}");
    }
    println!("\n{} adversarial inputs, all rejected", log.len());
}

/// The two public-input encodings of the accumulator point at infinity that
/// the deployed bytecode currently accepts at the decode layer.
///
/// This is a characterisation test, not an approval. Case B is the
/// always-false `and` guard in `load_acc_coord_shifted`: because the identity
/// flag is never subtracted, the probe fires on the *unflagged* `p - 1`
/// encoding and sets `is_id`, where correct code would fall through to
/// `ok := and(ok, iszero(decoded_zero))` and reject. Both reach the pairing
/// and both are rejected there for this proof, because the accumulator words
/// are transcript-absorbed. Fixed in current codegen; this pins the deployed
/// behaviour so a redeploy shows up as a diff here.
#[test]
fn deployed_wrap_verifier_accepts_two_infinity_encodings_at_the_decode_layer() {
    let dir = deployment_dir();
    let vk_src = std::fs::read_to_string(dir.join("Halo2VerifyingKey.sol")).unwrap();
    let ver_src = std::fs::read_to_string(dir.join("Halo2Verifier.sol")).unwrap();
    let calldata = fixture_calldata();

    let mut evm = Evm::default();
    let vk = evm.create(compile_solidity_with_runs(&vk_src, SOLC_OPTIMIZE_RUNS));
    let verifier =
        evm.create_with_address_arg(compile_solidity_with_runs(&ver_src, SOLC_OPTIMIZE_RUNS), vk);

    let accepted_gas = match evm.try_call_with_gas(verifier, calldata.clone(), GAS_CAP) {
        CallOutcome::Success { gas_used, .. } => gas_used,
        other => panic!("baseline proof must verify: {other:?}"),
    };

    // `p - 1` packed as seven radix-2^56 limbs: the codec's encoding of zero.
    let (sentinel_w0, sentinel_w1) = {
        let e = p() - Big::from(1u32);
        let mask = (Big::from(1u32) << LIMB_BITS) - Big::from(1u32);
        let mut w0 = Big::from(0u32);
        for i in 0..LIMBS_PER_WORD {
            w0 |= ((&e >> (LIMB_BITS * i as u32)) & &mask) << (LIMB_BITS * i as u32);
        }
        let mut w1 = Big::from(0u32);
        for i in LIMBS_PER_WORD..NUM_LIMBS {
            w1 |= ((&e >> (LIMB_BITS * i as u32)) & &mask)
                << (LIMB_BITS * (i - LIMBS_PER_WORD) as u32);
        }
        (w0, w1)
    };
    let flagged_w0 = &sentinel_w0 + (Big::from(1u32) << LIMB_BITS);

    let build = |x_word0: &Big| {
        let mut cd = calldata.clone();
        for point in 0..2usize {
            for (word, value) in [
                (0usize, x_word0.clone()),
                (1, sentinel_w1.clone()),
                (2, sentinel_w0.clone()),
                (3, sentinel_w1.clone()),
            ] {
                let off = acc_word_offset(point, word);
                cd[off..off + 32].copy_from_slice(&word_bytes(&value));
            }
        }
        cd
    };

    for (label, x_word0) in [
        (
            "A: canonical infinity (x = p-1 WITH the identity flag)",
            &flagged_w0,
        ),
        (
            "B: alternate infinity (x = p-1, NO identity flag)",
            &sentinel_w0,
        ),
    ] {
        match evm.try_call_with_gas(verifier, build(x_word0), GAS_CAP) {
            CallOutcome::Revert { gas_used, .. } => {
                let stage = classify(gas_used, accepted_gas);
                assert_eq!(
                    stage,
                    Stage::Algebra,
                    "{label}: expected the decoder to accept this and the pairing to reject it, \
                     but it was rejected at {stage:?} ({gas_used} gas)"
                );
                println!("{label}\n    decode accepted, pairing rejected, {gas_used} gas");
            }
            other => panic!("{label}: expected a revert at the pairing, got {other:?}"),
        }
    }
    println!(
        "\nBoth encodings clear the decoder. Correct behaviour would accept only A; \
         B is the always-false `and` guard at Halo2Verifier.sol:577."
    );
}
