// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Test, Log } from "./forge-std-min.sol";
import { PoseidonVerifier } from "../contracts/PoseidonVerifier.sol";
import { PoseidonVerifyingKey } from "../contracts/PoseidonVerifyingKey.sol";

/// @notice End-to-end Solidity verifier test running against the Prague EVM.
///
/// The test:
///   1. Deploys `PoseidonVerifyingKey` (tiny constants-only contract).
///   2. Deploys `PoseidonVerifier` wired to the VK contract's address.
///   3. Loads `fixtures/proof.bin` and `fixtures/instance.be` produced by
///      the Rust `cargo run --bin generate`.
///   4. Calls `verify(instance, proof)` and measures gas for each of the
///      verifier's internal phases via the `PhaseGas(name, gas)` event.
///   5. Dumps deployment gas, call gas, and every traced challenge / read /
///      pairing outcome to `fixtures/solidity_trace.json` so the Rust
///      harness can cross-check the two execution traces.
contract PoseidonVerifierTest is Test {
    PoseidonVerifier v;
    address vkAddr;

    uint256 public vkDeployGas;
    uint256 public verifierDeployGas;

    function setUp() public {
        uint256 g0 = gasleft();
        vkAddr = address(new PoseidonVerifyingKey());
        vkDeployGas = g0 - gasleft();

        g0 = gasleft();
        v = new PoseidonVerifier(vkAddr);
        verifierDeployGas = g0 - gasleft();
    }

    /// Unit test for the G1 decompression helper. Reads pre-computed
    /// (compressed, uncompressed) pairs from `fixtures/decomp_pairs.bin`
    /// (generated by `cargo run --bin generate`) and checks that the
    /// Solidity decompressor produces the exact EIP-2537 byte layout
    /// emitted by blst on the Rust side.
    function test_g1_decompression() public {
        bytes memory blob = vm.readFileBinary("fixtures/decomp_pairs.bin");
        require(blob.length > 0 && blob.length % 176 == 0, "bad fixture len");
        uint256 n = blob.length / 176;
        for (uint256 k = 0; k < n; k++) {
            bytes memory compressed = _slice(blob, k * 176, 48);
            bytes memory expected   = _slice(blob, k * 176 + 48, 128);
            bytes memory actual = v.decompressG1(compressed);
            require(actual.length == 128, "bad out len");
            for (uint256 i = 0; i < 128; i++) {
                require(actual[i] == expected[i], "decompression mismatch");
            }
        }
        emit log_named_uint("decompression cases verified", n);
    }

    function _slice(bytes memory b, uint256 off, uint256 len)
        internal pure returns (bytes memory out)
    {
        out = new bytes(len);
        for (uint256 i = 0; i < len; i++) out[i] = b[off + i];
    }

    /// Unit test for the scalar field + Lagrange-basis primitives.
    ///
    /// Reads `fixtures/algebra_fixtures.bin` produced by `cargo run --bin
    /// generate`:
    ///   [ 0.. 32)  omega
    ///   [32.. 64)  n  (Fr element)
    ///   [64.. 96)  x  (random challenge)
    ///   [96..128)  xn = x^n
    ///   [128..160) a
    ///   [160..192) a_inv
    ///   [192..224) N (big-endian uint256: number of Lagrange evals that follow)
    ///   [224..   ) L_0(x), L_1(x), ..., L_{N-1}(x)
    function test_algebra_primitives() public {
        bytes memory blob = vm.readFileBinary("fixtures/algebra_fixtures.bin");
        require(blob.length >= 224, "bad algebra fixture");

        uint256 omega  = _readUint(blob, 0);
        uint256 n      = _readUint(blob, 32);
        uint256 x      = _readUint(blob, 64);
        uint256 xn     = _readUint(blob, 96);
        uint256 a      = _readUint(blob, 128);
        uint256 aInv   = _readUint(blob, 160);
        uint256 nEvals = _readUint(blob, 192);
        require(blob.length == 224 + nEvals * 32, "fixture len mismatch");

        // 1) `frInv(a) == a_inv` (Fermat's little theorem via ModExp).
        require(v.frInv(a) == aInv, "frInv mismatch");

        // 2) `frPow(omega, n) == 1` (n-th root of unity).
        require(v.frPow(omega, n) == 1, "omega^n != 1");

        // 3) `rotateOmega(1, i, omega, n) == omega^i` for a few i values.
        for (int256 i = 0; i < 8; i++) {
            require(
                v.rotateOmega(1, i, omega, n) == v.frPow(omega, uint256(i)),
                "rotateOmega pos mismatch"
            );
        }

        // 4) Full domain Lagrange: L_i(x) for i in 0..n matches the Rust-
        //    computed `domain.l_i_range(x, xn, 0..n)`.
        uint256[] memory lSol = v.lagrangeIRange(x, xn, 0, int256(nEvals) - 1, omega, n);
        require(lSol.length == nEvals, "L len mismatch");
        for (uint256 i = 0; i < nEvals; i++) {
            uint256 expected = _readUint(blob, 224 + i * 32);
            require(lSol[i] == expected, "L_i mismatch");
        }

        // 5) Lagrange interpolation sanity: pick 3 distinct omega^i and
        //    their L_i(x) values, interpolate at x3 = x, and check we
        //    recover the expected sum (trivial identity since L_i(x) is
        //    itself a Lagrange polynomial evaluated at x).
        uint256[] memory pts = new uint256[](3);
        uint256[] memory evs = new uint256[](3);
        pts[0] = v.frPow(omega, 0);
        pts[1] = v.frPow(omega, 1);
        pts[2] = v.frPow(omega, 2);
        evs[0] = 11;
        evs[1] = 22;
        evs[2] = 33;
        // Evaluating at x = pts[1] must return evs[1] exactly.
        require(v.lagrangeInterpAtX3(pts, evs, pts[1]) == 22, "interp wrong");

        emit log_named_uint("algebra primitives ok", nEvals);
    }

    function _readUint(bytes memory b, uint256 off) internal pure returns (uint256 v_) {
        assembly { v_ := mload(add(add(b, 32), off)) }
    }

    /// Unit test for the gate-expression bytecode interpreter.
    ///
    /// The Rust generator serialises every gate polynomial of the
    /// ConstraintSystem into RPN bytecode (see src/expr_bytecode.rs),
    /// evaluates each polynomial against a deterministic environment
    /// (x, β, γ, θ, τ, l_0, l_last, l_blind, plus fixed/advice/instance/
    /// challenge query arrays), and writes both the bytecode and the
    /// Rust-computed expected value to `fixtures/gate_eval_fixture.bin`.
    /// This test replays the evaluation on-chain and asserts that the
    /// Solidity interpreter produces exactly the same Fr element.
    ///
    /// A mismatch here means either:
    ///   * the encoding in expr_bytecode.rs doesn't match the decoding
    ///     in PoseidonVerifier._evalBytecode, or
    ///   * the Rust-side self-check inside `generate` has silently
    ///     accepted a bogus bytecode.
    function test_gate_bytecode_interpreter() public {
        bytes memory blob = vm.readFileBinary("fixtures/gate_eval_fixture.bin");
        require(blob.length >= 256, "bad gate fixture");

        uint256[] memory env = new uint256[](8);
        for (uint256 i = 0; i < 8; i++) env[i] = _readUint(blob, i * 32);
        uint256 off = 256;

        (uint256[] memory fe, uint256 off1) = _readArr(blob, off);
        (uint256[] memory ae, uint256 off2) = _readArr(blob, off1);
        (uint256[] memory ie, uint256 off3) = _readArr(blob, off2);
        (uint256[] memory ch, uint256 off4) = _readArr(blob, off3);

        uint256 nGates = _readUint(blob, off4);
        uint256 cursor = off4 + 32;
        for (uint256 g = 0; g < nGates; g++) {
            uint256 bcLen = _readUint(blob, cursor);
            cursor += 32;
            bytes memory bc = new bytes(bcLen);
            for (uint256 k = 0; k < bcLen; k++) bc[k] = blob[cursor + k];
            cursor += bcLen;
            uint256 expected = _readUint(blob, cursor);
            cursor += 32;

            uint256 got = v.evalGateBytecode(bc, env, fe, ae, ie, ch);
            require(got == expected, "gate bytecode mismatch");
        }
        emit log_named_uint("gate bytecode polys verified", nGates);
    }

    function _readArr(bytes memory b, uint256 off) internal pure
        returns (uint256[] memory arr, uint256 next)
    {
        uint256 n = _readUint(b, off);
        off += 32;
        arr = new uint256[](n);
        for (uint256 i = 0; i < n; i++) {
            arr[i] = _readUint(b, off);
            off += 32;
        }
        next = off;
    }

    function test_verify_poseidon_proof() public {
        bytes memory proof = vm.readFileBinary("fixtures/proof.bin");
        bytes memory instanceBE = vm.readFileBinary("fixtures/instance.be");
        require(instanceBE.length == 32, "instance size");
        bytes32 instance;
        assembly { instance := mload(add(instanceBE, 32)) }

        // Record logs so we can aggregate per-phase gas and challenges.
        vm.recordLogs();
        uint256 g0 = gasleft();
        bool ok;
        try v.verify(instance, proof) returns (bool r) {
            ok = r;
        } catch {
            ok = false;
        }
        uint256 verifyGas = g0 - gasleft();

        Log[] memory logs = vm.getRecordedLogs();

        // Print structured benchmark report.
        _logBench("VK deploy",       vkDeployGas);
        _logBench("Verifier deploy", verifierDeployGas);
        _logBench("verify() total",  verifyGas);

        bytes32 phaseGasSig = keccak256("PhaseGas(string,uint256)");
        bytes32 challengeSig = keccak256("TraceChallenge(string,bytes32)");
        bytes32 readScalarSig = keccak256("TraceReadScalar(string,bytes32)");
        bytes32 readPointSig = keccak256("TraceReadPoint(string,bytes)");
        bytes32 pairingSig = keccak256("TracePairing(bool)");

        string memory trace = "[";
        bool first = true;
        for (uint256 i = 0; i < logs.length; i++) {
            if (logs[i].topics[0] == phaseGasSig) {
                (string memory name, uint256 g) = abi.decode(logs[i].data, (string, uint256));
                _logBench(string.concat("  . ", name), g);
            } else if (logs[i].topics[0] == challengeSig) {
                (string memory name, bytes32 fe) = abi.decode(logs[i].data, (string, bytes32));
                trace = _appendTrace(trace, first, "Challenge", name, _toHex(fe), "");
                first = false;
            } else if (logs[i].topics[0] == readScalarSig) {
                (string memory name, bytes32 fe) = abi.decode(logs[i].data, (string, bytes32));
                trace = _appendTrace(trace, first, "ReadScalar", name, _toHex(fe), "");
                first = false;
            } else if (logs[i].topics[0] == readPointSig) {
                (string memory name, bytes memory p) = abi.decode(logs[i].data, (string, bytes));
                trace = _appendTrace(trace, first, "ReadPoint", name, "", _toHexBytes(p));
                first = false;
            } else if (logs[i].topics[0] == pairingSig) {
                bool r = abi.decode(logs[i].data, (bool));
                trace = _appendTrace(trace, first, "PairingResult", r ? "true" : "false", "", "");
                first = false;
            }
        }
        trace = string.concat(trace, "]");
        vm.writeFile("fixtures/solidity_trace.json", trace);

        emit log_named_bool("verify_ok", ok);

        // Strict soundness assertion: the verifier MUST accept a valid
        // proof produced by the canonical Rust prover for the poseidon
        // example. When this assertion fails it means one of the
        // algebraically-sound layers is either missing or buggy:
        //   * `partially_evaluate_identities` (per-gate Solidity codegen),
        //   * `compute_linearization_commitment` MSM,
        //   * `multi_prepare` MSM (construct_intermediate_sets, Lagrange
        //     interpolation at x3, DualMSM),
        //   * instance eval via domain Lagrange basis for non-committed
        //     instance columns,
        //   * `l_0` / `l_last` / `l_blind` at x (permutation boundary),
        //   * or the real pairing RHS `e(C − v·G + x3·π, -G2)`.
        // The layers that ARE in place — full Keccak256 Fiat-Shamir
        // transcript, `parse_trace`, the `multi_prepare` reads (x1, x2,
        // f_com, x3, q_evals, x4, π), Fp-sqrt G1 decompression, Fr
        // arithmetic + Lagrange basis / interpolation, and the EIP-2537
        // pairing precompile wiring — are covered by the unit tests
        // above and by the Rust-side `rust_and_solidity_traces_match`
        // integration test in tests/forge.rs.
        require(ok, "verify(): valid proof was rejected");
    }

    /// Negative soundness assertion: flipping a single byte of the proof
    /// must cause `verify()` to return false (or revert). Guards against
    /// a trivial-accept implementation that short-circuits to `true`
    /// regardless of the input.
    function test_verify_rejects_mutated_proof() public {
        bytes memory proof = vm.readFileBinary("fixtures/proof.bin");
        bytes memory instanceBE = vm.readFileBinary("fixtures/instance.be");
        require(instanceBE.length == 32, "instance size");
        bytes32 instance;
        assembly { instance := mload(add(instanceBE, 32)) }

        // Mutate one byte in the middle of the proof (past the fixed
        // commitments prefix so we land in an evaluation or perm product).
        uint256 idx = proof.length / 2;
        proof[idx] = bytes1(uint8(proof[idx]) ^ 0x01);

        bool ok;
        try v.verify(instance, proof) returns (bool r) {
            ok = r;
        } catch {
            ok = false;
        }
        require(!ok, "verify() accepted a mutated proof");
        emit log_named_bool("mutation rejected", !ok);
    }

    event log_named_uint(string, uint256);
    event log_named_bool(string, bool);

    function _logBench(string memory name, uint256 g) internal {
        emit log_named_uint(name, g);
    }

    function _appendTrace(
        string memory acc,
        bool first,
        string memory kind,
        string memory name,
        string memory feHex,
        string memory pHex
    ) internal pure returns (string memory) {
        string memory sep = first ? "" : ",";
        if (bytes(pHex).length > 0) {
            return string.concat(
                acc, sep,
                "{\"kind\":\"", kind,
                "\",\"tag\":\"", name,
                "\",\"eip2537_hex\":\"", pHex,
                "\"}"
            );
        }
        return string.concat(
            acc, sep,
            "{\"kind\":\"", kind,
            "\",\"tag\":\"", name,
            "\",\"fe_be_hex\":\"", feHex,
            "\"}"
        );
    }

    function _toHex(bytes32 v) internal pure returns (string memory) {
        bytes memory alph = "0123456789abcdef";
        bytes memory out = new bytes(64);
        for (uint256 i = 0; i < 32; i++) {
            out[2 * i]     = alph[uint8(v[i]) >> 4];
            out[2 * i + 1] = alph[uint8(v[i]) & 0xf];
        }
        return string(out);
    }

    function _toHexBytes(bytes memory b) internal pure returns (string memory) {
        bytes memory alph = "0123456789abcdef";
        bytes memory out = new bytes(b.length * 2);
        for (uint256 i = 0; i < b.length; i++) {
            out[2 * i]     = alph[uint8(b[i]) >> 4];
            out[2 * i + 1] = alph[uint8(b[i]) & 0xf];
        }
        return string(out);
    }
}
