// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Test, Log } from "./forge-std-min.sol";
import { PoseidonVerifier } from "../contracts/PoseidonVerifier.sol";
import { PoseidonVerifyingKey } from "../contracts/PoseidonVerifyingKey.sol";

/// @notice End-to-end Solidity verifier test running against the Prague EVM.
///
/// The test:
///   1. Deploys `PoseidonVerifyingKey` (tiny constants-only contract).
///   2. Deploys `PoseidonVerifier` wired to the VK contract's address.
///   3. Loads `fixtures/proof.bin` and `fixtures/instance.be` produced by
///      the Rust `cargo run --bin generate`.
///   4. Calls `verify(instance, proof)` and measures gas for each of the
///      verifier's internal phases via the `PhaseGas(name, gas)` event.
///   5. Dumps deployment gas, call gas, and every traced challenge / read /
///      pairing outcome to `fixtures/solidity_trace.json` so the Rust
///      harness can cross-check the two execution traces.
contract PoseidonVerifierTest is Test {
    PoseidonVerifier v;
    address vkAddr;

    uint256 public vkDeployGas;
    uint256 public verifierDeployGas;

    function setUp() public {
        uint256 g0 = gasleft();
        vkAddr = address(new PoseidonVerifyingKey());
        vkDeployGas = g0 - gasleft();

        g0 = gasleft();
        v = new PoseidonVerifier(vkAddr);
        verifierDeployGas = g0 - gasleft();
    }

    /// Unit test for the G1 decompression helper. Reads pre-computed
    /// (compressed, uncompressed) pairs from `fixtures/decomp_pairs.bin`
    /// (generated by `cargo run --bin generate`) and checks that the
    /// Solidity decompressor produces the exact EIP-2537 byte layout
    /// emitted by blst on the Rust side.
    function test_g1_decompression() public {
        bytes memory blob = vm.readFileBinary("fixtures/decomp_pairs.bin");
        require(blob.length > 0 && blob.length % 176 == 0, "bad fixture len");
        uint256 n = blob.length / 176;
        for (uint256 k = 0; k < n; k++) {
            bytes memory compressed = _slice(blob, k * 176, 48);
            bytes memory expected   = _slice(blob, k * 176 + 48, 128);
            bytes memory actual = v.decompressG1(compressed);
            require(actual.length == 128, "bad out len");
            for (uint256 i = 0; i < 128; i++) {
                require(actual[i] == expected[i], "decompression mismatch");
            }
        }
        emit log_named_uint("decompression cases verified", n);
    }

    function _slice(bytes memory b, uint256 off, uint256 len)
        internal pure returns (bytes memory out)
    {
        out = new bytes(len);
        for (uint256 i = 0; i < len; i++) out[i] = b[off + i];
    }

    /// Unit test for the scalar field + Lagrange-basis primitives.
    ///
    /// Reads `fixtures/algebra_fixtures.bin` produced by `cargo run --bin
    /// generate`:
    ///   [ 0.. 32)  omega
    ///   [32.. 64)  n  (Fr element)
    ///   [64.. 96)  x  (random challenge)
    ///   [96..128)  xn = x^n
    ///   [128..160) a
    ///   [160..192) a_inv
    ///   [192..224) N (big-endian uint256: number of Lagrange evals that follow)
    ///   [224..   ) L_0(x), L_1(x), ..., L_{N-1}(x)
    function test_algebra_primitives() public {
        bytes memory blob = vm.readFileBinary("fixtures/algebra_fixtures.bin");
        require(blob.length >= 224, "bad algebra fixture");

        uint256 omega  = _readUint(blob, 0);
        uint256 n      = _readUint(blob, 32);
        uint256 x      = _readUint(blob, 64);
        uint256 xn     = _readUint(blob, 96);
        uint256 a      = _readUint(blob, 128);
        uint256 aInv   = _readUint(blob, 160);
        uint256 nEvals = _readUint(blob, 192);
        require(blob.length == 224 + nEvals * 32, "fixture len mismatch");

        // 1) `frInv(a) == a_inv` (Fermat's little theorem via ModExp).
        require(v.frInv(a) == aInv, "frInv mismatch");

        // 2) `frPow(omega, n) == 1` (n-th root of unity).
        require(v.frPow(omega, n) == 1, "omega^n != 1");

        // 3) `rotateOmega(1, i, omega, n) == omega^i` for a few i values.
        for (int256 i = 0; i < 8; i++) {
            require(
                v.rotateOmega(1, i, omega, n) == v.frPow(omega, uint256(i)),
                "rotateOmega pos mismatch"
            );
        }

        // 4) Full domain Lagrange: L_i(x) for i in 0..n matches the Rust-
        //    computed `domain.l_i_range(x, xn, 0..n)`.
        uint256[] memory lSol = v.lagrangeIRange(x, xn, 0, int256(nEvals) - 1, omega, n);
        require(lSol.length == nEvals, "L len mismatch");
        for (uint256 i = 0; i < nEvals; i++) {
            uint256 expected = _readUint(blob, 224 + i * 32);
            require(lSol[i] == expected, "L_i mismatch");
        }

        // 5) Lagrange interpolation sanity: pick 3 distinct omega^i and
        //    their L_i(x) values, interpolate at x3 = x, and check we
        //    recover the expected sum (trivial identity since L_i(x) is
        //    itself a Lagrange polynomial evaluated at x).
        uint256[] memory pts = new uint256[](3);
        uint256[] memory evs = new uint256[](3);
        pts[0] = v.frPow(omega, 0);
        pts[1] = v.frPow(omega, 1);
        pts[2] = v.frPow(omega, 2);
        evs[0] = 11;
        evs[1] = 22;
        evs[2] = 33;
        // Evaluating at x = pts[1] must return evs[1] exactly.
        require(v.lagrangeInterpAtX3(pts, evs, pts[1]) == 22, "interp wrong");

        emit log_named_uint("algebra primitives ok", nEvals);
    }

    function _readUint(bytes memory b, uint256 off) internal pure returns (uint256 v_) {
        assembly { v_ := mload(add(add(b, 32), off)) }
    }

    /// Unit test for the gate-expression bytecode interpreter.
    ///
    /// The Rust generator serialises every gate polynomial of the
    /// ConstraintSystem into RPN bytecode (see src/expr_bytecode.rs),
    /// evaluates each polynomial against a deterministic environment
    /// (x, β, γ, θ, τ, l_0, l_last, l_blind, plus fixed/advice/instance/
    /// challenge query arrays), and writes both the bytecode and the
    /// Rust-computed expected value to `fixtures/gate_eval_fixture.bin`.
    /// This test replays the evaluation on-chain and asserts that the
    /// Solidity interpreter produces exactly the same Fr element.
    ///
    /// A mismatch here means either:
    ///   * the encoding in expr_bytecode.rs doesn't match the decoding
    ///     in PoseidonVerifier._evalBytecode, or
    ///   * the Rust-side self-check inside `generate` has silently
    ///     accepted a bogus bytecode.
    function test_gate_bytecode_interpreter() public {
        bytes memory blob = vm.readFileBinary("fixtures/gate_eval_fixture.bin");
        require(blob.length >= 256, "bad gate fixture");

        uint256[] memory env = new uint256[](8);
        for (uint256 i = 0; i < 8; i++) env[i] = _readUint(blob, i * 32);
        uint256 off = 256;

        (uint256[] memory fe, uint256 off1) = _readArr(blob, off);
        (uint256[] memory ae, uint256 off2) = _readArr(blob, off1);
        (uint256[] memory ie, uint256 off3) = _readArr(blob, off2);
        (uint256[] memory ch, uint256 off4) = _readArr(blob, off3);

        uint256 nGates = _readUint(blob, off4);
        uint256 cursor = off4 + 32;
        for (uint256 g = 0; g < nGates; g++) {
            uint256 bcLen = _readUint(blob, cursor);
            cursor += 32;
            bytes memory bc = new bytes(bcLen);
            for (uint256 k = 0; k < bcLen; k++) bc[k] = blob[cursor + k];
            cursor += bcLen;
            uint256 expected = _readUint(blob, cursor);
            cursor += 32;

            uint256 got = v.evalGateBytecode(bc, env, fe, ae, ie, ch);
            require(got == expected, "gate bytecode mismatch");
        }
        emit log_named_uint("gate bytecode polys verified", nGates);
    }

    function _readArr(bytes memory b, uint256 off) internal pure
        returns (uint256[] memory arr, uint256 next)
    {
        uint256 n = _readUint(b, off);
        off += 32;
        arr = new uint256[](n);
        for (uint256 i = 0; i < n; i++) {
            arr[i] = _readUint(b, off);
            off += 32;
        }
        next = off;
    }

    /// Phase A1 step 2: permutation-expressions equivalence test.
    ///
    /// Reads `fixtures/perm_expressions_fixture.bin` produced by the
    /// Rust-side replica of `permutation::expressions`, feeds the
    /// inputs into the Solidity `permExpressions` wrapper, and
    /// asserts every emitted expression matches the Rust-computed
    /// expected value byte-for-byte. For the poseidon circuit this
    /// exercises 7 expressions across 3 chunks × 8 permutation
    /// columns.
    function test_perm_expressions() public {
        bytes memory blob = vm.readFileBinary("fixtures/perm_expressions_fixture.bin");
        uint256 off = 0;
        uint256[6] memory envScalars;
        for (uint256 i = 0; i < 6; i++) { envScalars[i] = _readUint(blob, off); off += 32; }
        uint256 deltaFromFixture = _readUint(blob, off); off += 32;
        // Sanity: contract's hard-coded FR_DELTA matches the Rust-
        // computed DELTA (otherwise main-chunk constraints diverge).
        // Using a sentinel call that exposes FR_DELTA via _frDeltaPow(1).
        require(deltaFromFixture == v.frDeltaPow(1), "FR_DELTA constant mismatch");

        uint256 nChunks = _readUint(blob, off); off += 32;
        uint256[] memory setsFlat = new uint256[](nChunks * 4);
        for (uint256 i = 0; i < nChunks; i++) {
            setsFlat[4 * i]     = _readUint(blob, off);            // prod
            setsFlat[4 * i + 1] = _readUint(blob, off + 32);       // next
            setsFlat[4 * i + 2] = _readUint(blob, off + 64);       // last
            setsFlat[4 * i + 3] = uint8(blob[off + 96]);           // hasLast
            off += 128; // 3*32 + 32 (1 byte + 31 pad)
        }

        (uint256[] memory permEvals, uint256 off1) = _readArr(blob, off);
        (uint256[] memory adviceEvals, uint256 off2) = _readArr(blob, off1);
        (uint256[] memory fixedEvals, uint256 off3) = _readArr(blob, off2);
        (uint256[] memory instanceEvals, uint256 off4) = _readArr(blob, off3);
        (uint256[] memory expected, uint256 _off5) = _readArr(blob, off4);

        // Load column metadata from the VK blob.
        bytes memory vkBlob = vkAddr.code;
        (uint8[] memory colKinds, uint16[] memory colQueryIdxs, uint256 chunkLen) =
            _loadPermColumnMetadata(vkBlob);

        uint256[] memory got = v.permExpressions(
            envScalars, setsFlat, permEvals, adviceEvals, fixedEvals, instanceEvals,
            colKinds, colQueryIdxs, chunkLen
        );

        require(got.length == expected.length, "perm expr len mismatch");
        for (uint256 i = 0; i < got.length; i++) {
            require(got[i] == expected[i], "perm expression mismatch");
        }
        emit log_named_uint("perm expressions verified", got.length);
    }

    /// Locate the permutation metadata section inside the VK blob.
    /// After Phase A2a appended the lookup-bytecode section, the
    /// permutation section is no longer at the tail; it sits
    /// immediately before the `u32 num_lookups` header of the
    /// lookup section. We recover its position via the same
    /// candidate-nCols scan used by `_findLookupSection`.
    function _loadPermColumnMetadata(bytes memory blob) internal pure
        returns (uint8[] memory colKinds, uint16[] memory colQueryIdxs, uint256 chunkLen)
    {
        uint256 L = blob.length;
        uint256 nCols = 0;
        uint256 tailStart = 0;
        for (uint256 candidate = 1; candidate <= 256; candidate++) {
            for (uint256 pos = 0; pos + 8 + 3 * candidate + 4 <= L; pos++) {
                uint32 clen = _readU32(blob, pos);
                uint32 nc = _readU32(blob, pos + 4);
                if (nc != candidate || clen >= 64) continue;
                uint256 lookupStart = pos + 8 + 3 * candidate;
                uint32 nLookups = _readU32(blob, lookupStart);
                if (nLookups == 0 || nLookups > 16) continue;
                if (_validateLookupSection(blob, lookupStart, nLookups, L)) {
                    nCols = candidate;
                    chunkLen = clen;
                    tailStart = pos;
                    break;
                }
            }
            if (nCols > 0) break;
        }
        require(nCols > 0, "perm metadata not found");
        colKinds = new uint8[](nCols);
        colQueryIdxs = new uint16[](nCols);
        uint256 cursor = tailStart + 8;
        for (uint256 i = 0; i < nCols; i++) {
            colKinds[i] = uint8(blob[cursor]);
            colQueryIdxs[i] = (uint16(uint8(blob[cursor + 1])) << 8) | uint16(uint8(blob[cursor + 2]));
            cursor += 3;
        }
    }

    function _readU32(bytes memory b, uint256 off) internal pure returns (uint32 v_) {
        v_ = (uint32(uint8(b[off])) << 24)
           | (uint32(uint8(b[off + 1])) << 16)
           | (uint32(uint8(b[off + 2])) << 8)
           |  uint32(uint8(b[off + 3]));
    }

    /// Phase A2a: lookup-expressions equivalence test.
    ///
    /// Mirrors `test_perm_expressions` but for the logup argument.
    /// Reads `fixtures/lookup_expressions_fixture.bin` produced by
    /// the Rust-side replica of `logup::Evaluated::expressions`,
    /// locates the lookup-bytecode section at the tail of the VK
    /// blob (just after the permutation section), and asserts the
    /// Solidity output matches expression-for-expression. For the
    /// poseidon circuit this exercises 3 expressions (1 boundary +
    /// 1 helper + 1 accumulator) across the argument's single
    /// chunk.
    function test_lookup_expressions() public {
        bytes memory blob = vm.readFileBinary("fixtures/lookup_expressions_fixture.bin");
        uint256 off = 0;
        uint256[8] memory scalars;
        for (uint256 i = 0; i < 8; i++) { scalars[i] = _readUint(blob, off); off += 32; }
        (uint256[] memory helperEvals, uint256 off1) = _readArr(blob, off);
        (uint256[] memory adviceEvals, uint256 off2) = _readArr(blob, off1);
        (uint256[] memory fixedEvals, uint256 off3) = _readArr(blob, off2);
        (uint256[] memory instanceEvals, uint256 off4) = _readArr(blob, off3);
        (uint256[] memory challenges, uint256 off5) = _readArr(blob, off4);
        (uint256[] memory expected, ) = _readArr(blob, off5);

        uint256 sectionOffset = _findLookupSection();

        uint256[] memory got = v.lookupExpressions(
            vkAddr, sectionOffset, scalars, helperEvals,
            adviceEvals, fixedEvals, instanceEvals, challenges
        );

        require(got.length == expected.length, "lookup expr len mismatch");
        for (uint256 i = 0; i < got.length; i++) {
            require(got[i] == expected[i], "lookup expression mismatch");
        }
        emit log_named_uint("lookup expressions verified", got.length);
    }

    /// Find where the lookup-bytecode section starts inside the VK
    /// blob. The layout is append-only:
    ///   ... gate bytecode, permutation metadata, lookup bytecode
    /// The permutation section ends at a known tail offset (we
    /// computed it for test_perm_expressions). The lookup section
    /// follows immediately. Since the permutation section's trailing
    /// byte count is `8 + 3*nCols`, we recover nCols the same way
    /// `_loadPermColumnMetadata` does, but we scan _beyond_ the end
    /// of the permutation tail — the lookup section itself has its
    /// own u32 num_lookups header and a variable-length tail, so we
    /// can't just compute \"L - offset\" numerically.
    ///
    /// Approach: walk from the end of the permutation section (which
    /// is recoverable by locating where `u32 permutation_chunk_len`
    /// + `u32 num_cols` + `num_cols*3` bytes start). To find that
    /// start, we reuse the size-scanning logic by trying candidate
    /// `nLookups` and bytecode lengths — but this is fragile, so we
    /// instead call `_loadPermColumnMetadata` to recover the
    /// permutation tail length and infer the section boundary.
    function _findLookupSection() internal view returns (uint256) {
        bytes memory vkBlob = vkAddr.code;
        // _loadPermColumnMetadata finds the permutation section; its
        // start is (L - (8 + 3*nCols) - lookup_section_len). We don't
        // yet know lookup_section_len; but the permutation section
        // appears before lookups, so the LOOKUP SECTION STARTS
        // IMMEDIATELY AFTER THE PERMUTATION SECTION.
        //
        // Recover the permutation section's END by iterating the same
        // way as _loadPermColumnMetadata but recording the position:
        //    tail_before_lookup_section = position of `u32 num_lookups`
        // This equals: (position where _loadPermColumnMetadata found
        // its candidate u32 pair) + 8 + 3*nCols.
        uint256 L = vkBlob.length;
        for (uint256 candidate = 1; candidate <= 256; candidate++) {
            // We want to find the permutation section at the MIDDLE
            // of the blob (no longer the end). The section length is
            // 8 + 3*candidate. Scan for its header.
            // Since the layout is append-only and the permutation
            // section is IMMEDIATELY followed by the lookup section,
            // we look for a position `pos` in [0, L) such that:
            //   * vkBlob[pos..pos+4] reads as chunkLen (< 64)
            //   * vkBlob[pos+4..pos+8] reads as candidate  (the number of perm cols)
            //   * at pos+8+3*candidate, a plausible u32 num_lookups
            //     (< 16) starts.
            // The position is the start of the permutation metadata.
            // We scan from high offsets (trailing lookup section is
            // typically the biggest) down.
            for (uint256 tailStart = 0; tailStart + 8 + 3 * candidate < L; tailStart++) {
                uint32 clen = _readU32(vkBlob, tailStart);
                uint32 nc = _readU32(vkBlob, tailStart + 4);
                if (nc != candidate || clen >= 64) continue;
                uint256 lookupStart = tailStart + 8 + 3 * candidate;
                if (lookupStart + 4 > L) continue;
                uint32 nLookups = _readU32(vkBlob, lookupStart);
                if (nLookups == 0 || nLookups > 16) continue;
                // Sanity-check by stepping through: for each lookup,
                // read the lengths and verify they stay within L.
                if (_validateLookupSection(vkBlob, lookupStart, nLookups, L)) {
                    return lookupStart;
                }
            }
        }
        revert("lookup section not found");
    }

    function _validateLookupSection(
        bytes memory blob, uint256 startAfterHeader, uint32 nLookups, uint256 L
    ) internal pure returns (bool) {
        uint256 p = _walkLookupSection(blob, startAfterHeader, nLookups, L);
        if (p == type(uint256).max) return false;
        // Trashcan section follows: u32 nTrashcans + per-trashcan.
        if (p + 4 > L) return false;
        uint32 nTrash = _readU32(blob, p); p += 4;
        if (nTrash > 16) return false;
        for (uint32 t = 0; t < nTrash; t++) {
            if (p + 4 > L) return false;
            uint32 selLen = _readU32(blob, p); p += 4 + selLen; if (p > L) return false;
            if (p + 4 > L) return false;
            uint32 nC = _readU32(blob, p); p += 4;
            for (uint32 i = 0; i < nC; i++) {
                if (p + 4 > L) return false;
                uint32 l = _readU32(blob, p); p += 4 + l; if (p > L) return false;
            }
        }
        return p == L;
    }

    function _walkLookupSection(
        bytes memory blob, uint256 startAfterHeader, uint32 nLookups, uint256 L
    ) internal pure returns (uint256) {
        uint256 p = startAfterHeader + 4;
        for (uint32 lk = 0; lk < nLookups; lk++) {
            if (p + 4 > L) return type(uint256).max;
            uint32 selLen = _readU32(blob, p); p += 4 + selLen; if (p > L) return type(uint256).max;
            if (p + 4 > L) return type(uint256).max;
            uint32 nTable = _readU32(blob, p); p += 4;
            for (uint32 i = 0; i < nTable; i++) {
                if (p + 4 > L) return type(uint256).max;
                uint32 l = _readU32(blob, p); p += 4 + l; if (p > L) return type(uint256).max;
            }
            if (p + 4 > L) return type(uint256).max;
            uint32 nChunks = _readU32(blob, p); p += 4;
            for (uint32 c = 0; c < nChunks; c++) {
                if (p + 4 > L) return type(uint256).max;
                uint32 nPar = _readU32(blob, p); p += 4;
                for (uint32 pp = 0; pp < nPar; pp++) {
                    if (p + 4 > L) return type(uint256).max;
                    uint32 nCols = _readU32(blob, p); p += 4;
                    for (uint32 k = 0; k < nCols; k++) {
                        if (p + 4 > L) return type(uint256).max;
                        uint32 l = _readU32(blob, p); p += 4 + l; if (p > L) return type(uint256).max;
                    }
                }
            }
        }
        return p;
    }

    /// Phase A2b: trashcan-expressions equivalence test.
    function test_trash_expressions() public {
        bytes memory blob = vm.readFileBinary("fixtures/trashcan_expressions_fixture.bin");
        uint256 off = 0;
        uint256 trashChallenge = _readUint(blob, off); off += 32;
        (uint256[] memory trashEvals, uint256 off1) = _readArr(blob, off);
        (uint256[] memory adviceEvals, uint256 off2) = _readArr(blob, off1);
        (uint256[] memory fixedEvals, uint256 off3) = _readArr(blob, off2);
        (uint256[] memory instanceEvals, uint256 off4) = _readArr(blob, off3);
        (uint256[] memory challenges, uint256 off5) = _readArr(blob, off4);
        (uint256[] memory expected, ) = _readArr(blob, off5);

        uint256 lookupOffset = _findLookupSection();
        uint256 trashOffset = _findTrashSection(lookupOffset);

        uint256[] memory got = v.trashExpressions(
            vkAddr, trashOffset, trashChallenge, trashEvals,
            adviceEvals, fixedEvals, instanceEvals, challenges
        );

        require(got.length == expected.length, "trash expr len mismatch");
        for (uint256 i = 0; i < got.length; i++) {
            require(got[i] == expected[i], "trash expression mismatch");
        }
        emit log_named_uint("trash expressions verified", got.length);
    }

    function _findTrashSection(uint256 lookupOffset) internal view returns (uint256) {
        bytes memory vkBlob = vkAddr.code;
        uint256 L = vkBlob.length;
        uint32 nLookups = _readU32(vkBlob, lookupOffset);
        uint256 afterLookups = _walkLookupSection(vkBlob, lookupOffset, nLookups, L);
        require(afterLookups != type(uint256).max && afterLookups + 4 <= L, "trash section not found");
        return afterLookups;
    }

    function test_verify_poseidon_proof() public {
        bytes memory proof = vm.readFileBinary("fixtures/proof.bin");
        bytes memory instanceBE = vm.readFileBinary("fixtures/instance.be");
        require(instanceBE.length == 32, "instance size");
        bytes32 instance;
        assembly { instance := mload(add(instanceBE, 32)) }

        // Record logs so we can aggregate per-phase gas and challenges.
        vm.recordLogs();
        uint256 g0 = gasleft();
        bool ok;
        try v.verify(instance, proof) returns (bool r) {
            ok = r;
        } catch {
            ok = false;
        }
        uint256 verifyGas = g0 - gasleft();

        Log[] memory logs = vm.getRecordedLogs();

        // Print structured benchmark report.
        _logBench("VK deploy",       vkDeployGas);
        _logBench("Verifier deploy", verifierDeployGas);
        _logBench("verify() total",  verifyGas);

        bytes32 phaseGasSig = keccak256("PhaseGas(string,uint256)");
        bytes32 challengeSig = keccak256("TraceChallenge(string,bytes32)");
        bytes32 readScalarSig = keccak256("TraceReadScalar(string,bytes32)");
        bytes32 readPointSig = keccak256("TraceReadPoint(string,bytes)");
        bytes32 pairingSig = keccak256("TracePairing(bool)");

        string memory trace = "[";
        bool first = true;
        for (uint256 i = 0; i < logs.length; i++) {
            if (logs[i].topics[0] == phaseGasSig) {
                (string memory name, uint256 g) = abi.decode(logs[i].data, (string, uint256));
                _logBench(string.concat("  . ", name), g);
            } else if (logs[i].topics[0] == challengeSig) {
                (string memory name, bytes32 fe) = abi.decode(logs[i].data, (string, bytes32));
                trace = _appendTrace(trace, first, "Challenge", name, _toHex(fe), "");
                first = false;
            } else if (logs[i].topics[0] == readScalarSig) {
                (string memory name, bytes32 fe) = abi.decode(logs[i].data, (string, bytes32));
                trace = _appendTrace(trace, first, "ReadScalar", name, _toHex(fe), "");
                first = false;
            } else if (logs[i].topics[0] == readPointSig) {
                (string memory name, bytes memory p) = abi.decode(logs[i].data, (string, bytes));
                trace = _appendTrace(trace, first, "ReadPoint", name, "", _toHexBytes(p));
                first = false;
            } else if (logs[i].topics[0] == pairingSig) {
                bool r = abi.decode(logs[i].data, (bool));
                trace = _appendTrace(trace, first, "PairingResult", r ? "true" : "false", "", "");
                first = false;
            }
        }
        trace = string.concat(trace, "]");
        vm.writeFile("fixtures/solidity_trace.json", trace);

        emit log_named_bool("verify_ok", ok);

        // Strict soundness assertion: the verifier MUST accept a valid
        // proof produced by the canonical Rust prover for the poseidon
        // example. When this assertion fails it means one of the
        // algebraically-sound layers is either missing or buggy:
        //   * `partially_evaluate_identities` (per-gate Solidity codegen),
        //   * `compute_linearization_commitment` MSM,
        //   * `multi_prepare` MSM (construct_intermediate_sets, Lagrange
        //     interpolation at x3, DualMSM),
        //   * instance eval via domain Lagrange basis for non-committed
        //     instance columns,
        //   * `l_0` / `l_last` / `l_blind` at x (permutation boundary),
        //   * or the real pairing RHS `e(C − v·G + x3·π, -G2)`.
        // The layers that ARE in place — full Keccak256 Fiat-Shamir
        // transcript, `parse_trace`, the `multi_prepare` reads (x1, x2,
        // f_com, x3, q_evals, x4, π), Fp-sqrt G1 decompression, Fr
        // arithmetic + Lagrange basis / interpolation, and the EIP-2537
        // pairing precompile wiring — are covered by the unit tests
        // above and by the Rust-side `rust_and_solidity_traces_match`
        // integration test in tests/forge.rs.
        require(ok, "verify(): valid proof was rejected");
    }

    /// Negative soundness assertion: flipping a single byte of the proof
    /// must cause `verify()` to return false (or revert). Guards against
    /// a trivial-accept implementation that short-circuits to `true`
    /// regardless of the input.
    function test_verify_rejects_mutated_proof() public {
        bytes memory proof = vm.readFileBinary("fixtures/proof.bin");
        bytes memory instanceBE = vm.readFileBinary("fixtures/instance.be");
        require(instanceBE.length == 32, "instance size");
        bytes32 instance;
        assembly { instance := mload(add(instanceBE, 32)) }

        // Mutate one byte in the middle of the proof (past the fixed
        // commitments prefix so we land in an evaluation or perm product).
        uint256 idx = proof.length / 2;
        proof[idx] = bytes1(uint8(proof[idx]) ^ 0x01);

        bool ok;
        try v.verify(instance, proof) returns (bool r) {
            ok = r;
        } catch {
            ok = false;
        }
        require(!ok, "verify() accepted a mutated proof");
        emit log_named_bool("mutation rejected", !ok);
    }

    event log_named_uint(string, uint256);
    event log_named_bool(string, bool);

    function _logBench(string memory name, uint256 g) internal {
        emit log_named_uint(name, g);
    }

    function _appendTrace(
        string memory acc,
        bool first,
        string memory kind,
        string memory name,
        string memory feHex,
        string memory pHex
    ) internal pure returns (string memory) {
        string memory sep = first ? "" : ",";
        if (bytes(pHex).length > 0) {
            return string.concat(
                acc, sep,
                "{\"kind\":\"", kind,
                "\",\"tag\":\"", name,
                "\",\"eip2537_hex\":\"", pHex,
                "\"}"
            );
        }
        return string.concat(
            acc, sep,
            "{\"kind\":\"", kind,
            "\",\"tag\":\"", name,
            "\",\"fe_be_hex\":\"", feHex,
            "\"}"
        );
    }

    function _toHex(bytes32 v) internal pure returns (string memory) {
        bytes memory alph = "0123456789abcdef";
        bytes memory out = new bytes(64);
        for (uint256 i = 0; i < 32; i++) {
            out[2 * i]     = alph[uint8(v[i]) >> 4];
            out[2 * i + 1] = alph[uint8(v[i]) & 0xf];
        }
        return string(out);
    }

    function _toHexBytes(bytes memory b) internal pure returns (string memory) {
        bytes memory alph = "0123456789abcdef";
        bytes memory out = new bytes(b.length * 2);
        for (uint256 i = 0; i < b.length; i++) {
            out[2 * i]     = alph[uint8(b[i]) >> 4];
            out[2 * i + 1] = alph[uint8(b[i]) & 0xf];
        }
        return string(out);
    }
}
